### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by changjonathanc** [chiphuyen/just-pandas-things#2]
In `just-pandas-things.ipynb`

> Note: You can also just use df.loc[0, "Review"] to calculate the memory address to retrieve the item. Its performance is comparable to gret row then get review.

`gret row then get review` should be `get review then get row`?

**Comment by kamalmemon** [comment]
Also, in `2.2.2 Raise an error`

> I believe SettingWithCopyWarning should be an Exemption instead of a warning.

`Exemption` should be `Exception` here.

**Comment by chiphuyen** [comment]
Fixed both. Thanks @cccntu  and @kamalmemon !

**Comment by loodvn** [comment]
Proposed a few little typo fixes in #13 👍
